[package]
name = "hpke-rs"
version = "0.3.0-alpha.2"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
documentation = "https://docs.rs/hpke-rs"
description = "HPKE Implementation"
readme = "Readme.md"
repository = "https://github.com/cryspen/hpke-rs"
exclude = ["/tests"]

[workspace]
members = ["traits", "libcrux_provider", "rust_crypto_provider", "."]

[dependencies]
log = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
tls_codec = { version = "0.4.2", features = ["derive"], optional = true }
zeroize = { version = "1.5", features = ["zeroize_derive"] }
hpke-rs-crypto = { version = "0.3.0-alpha.2", path = "./traits", default-features = false }
rand_core = { version = "0.9", default-features = false }
libcrux-sha3 = { version = "0.0.3-alpha.3" }
hpke-rs-rust-crypto = { version = "0.3.0-alpha.2", path = "./rust_crypto_provider", default-features = false, optional = true }
hpke-rs-libcrux = { version = "0.3.0-alpha.2", path = "./libcrux_provider", default-features = false, optional = true }

[features]
default = []
std = [
    "rand_core/std",
    "hpke-rs-crypto/std",
    "hpke-rs-rust-crypto?/std",
    "hpke-rs-libcrux?/std",
]
serialization = ["serde", "tls_codec", "tls_codec/serde", "std"]
hazmat = []
rustcrypto = ["dep:hpke-rs-rust-crypto"]
libcrux = ["dep:hpke-rs-libcrux"]

hpke-test = ["std"]
hpke-test-prng = [] # ⚠️ Enable testing PRNG - DO NOT USE

[dev-dependencies]
hpke-rs-crypto = { version = "0.3.0-alpha.2", path = "./traits", features = [
    "std",
] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4"
rayon = "1.5"
hpke-rs = { path = ".", features = ["hpke-test", "hazmat"] }
hpke-rs-rust-crypto = { version = "0.3.0-alpha.2", path = "./rust_crypto_provider", features = [
    "deterministic-prng",
] }
hpke-rs-libcrux = { version = "0.3.0-alpha.2", path = "./libcrux_provider", features = [
    "deterministic-prng",
] }
rand = { version = "0.9" }
pretty_env_logger = "0.5"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "manual_benches"
harness = false
